name: Pull Request Build

on: [pull_request]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args:
                      pack
              env:
                  WORKING_DIR: ./s3
            - name: Ballerina Test
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args:
                      test --test-report --code-coverage --coverage-format=xml
              env:
                  ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
                  SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
                  REGION: ${{ secrets.REGION }}
                  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
                  WORKING_DIR: ./s3

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
